Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/04/2023
Var
// Seção de Declarações das variáveis 
  int : teste

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  teste = 10
  escreval(teste)

Fimalgoritmo